name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Connect to server
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.PROD_VM }} 'cd /srv/platzkiecker && git pull'

      - name: stop application
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.PROD_VM }} 'cd /srv/platzkiecker && docker compose -f docker-compose.prod.yml down'
        continue-on-error: true

      - name: Build and run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.PROD_VM }} 'cd /srv/platzkiecker && docker compose -f docker-compose.prod.yml up -d --build'
